project:
  type: website
  output-dir: docs
  resources:
    - CNAME

website:
  title: "Brandon Dale Koepke"
  google-analytics: "G-XLHQLE1P7K"
  bread-crumbs: true
  site-url: https://finitemoment.com
  repo-url: https://github.com/bdkoepke/fmblog
  reader-mode: true
  favicon: logo.png
  twitter-card:
    creator: "@bdkoepke"
  open-graph: true
  comments:
    giscus:
      repo: bdkoepke/fmblog
  navbar:
    logo: finite_moment.png
    right:
      - about.qmd
      - icon: envelope-at
        href: mailto:brandon@finitemoment.com
      - icon: github
        href: https://github.com/bdkoepke
      - icon: twitter
        href: https://twitter.com/bdkoepke
      - icon: linkedin
        href: https://linkedin.com/in/bdkoepke
      - icon: rss
        href: index.xml
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    mainfont: "Computer Modern Serif"
