project:
  type: website
  output-dir: docs

website:
  title: "Finite Moment"
  site-url: https://finitemoment.com
  favicon: logo.png
  twitter-card:
    creator: "@bdkoepke"
  open-graph: true
  comments:
    giscus:
      repo: bdkoepke/fmblog
  navbar:
    right:
      - about.qmd
      - icon: envelope-at
        href: mailto:brandon@finitemoment.com
      - icon: github
        href: https://github.com/bdkoepke
      - icon: twitter
        href: https://twitter.com/bdkoepke
      - icon: linkedin
        href: https://linkedin.com/in/bdkoepke
      - icon: rss
        href: index.xml
format:
  html:
    theme: flatly
    css: styles.css
    toc: true
